### ISSUE TITLE
Ajout Prénom , Nom et email dans le readme

### ISSUE THREAD

**Issue by MamadouDjigo** [masto42/jupyterworkflow#1]
Bonjour @masto42 ,
peux tu ajouter ton prénom, nom et email dans le README?

**Comment by masto42** [comment]
Bonjour monsieur Djigo, j'ai ajouté mon prénom,  mon nom et mon mail comme
demandé.

Cordialement Fall Mahanta.

Le ven. 16 août 2019 à 08:45, Mamadou DJIGO <notifications@github.com> a
écrit :
